import Head from "next/head";
import styles from "@/styles/Home.module.css";
import axios from "axios";

const endpoint = 'https://www.devmedia.com.br/projetos-api/ufs';
const listaUfs = (await axios.get(endpoint)).data;

export default function Home() {
  return (
    <>
      <Head>
        <title>Consulta Estados</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <header className={styles.header}>
          <h1>Consulta Estados</h1>
        </header>
        <main>
         <table className={styles.tabela}>
          <thead>
            <tr>
              <th>ID</th>
              <th>UF</th>
              <th>Nome</th>
            </tr>
          </thead>
          <tbody>
          {
            listaUfs.map((dadosUF, index) => (
              <tr key={index}>
                <td>{dadosUF.id}</td>
                <td>{dadosUF.uf}</td>
                <td>{dadosUF.nome}</td>
              </tr>
            ))
          }
          </tbody>
         </table>
        </main>
      </div>
    </>
  );
}
