import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { retornaUfs } from "./servicos/ufs.js";

const listaUfs = await retornaUfs();

export default function Home() {
  return (
    <>
      <Head>
        <title>Consulta Estados</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <header className={styles.header}>
          <h1>Consulta Estados</h1>
        </header>
        <main>
         <table className={styles.tabela}>
          <thead>
            <tr>
              <th>ID</th>
              <th>UF</th>
              <th>Nome</th>
            </tr>
          </thead>
          <tbody>
          {
            Array.isArray(listaUfs) ?
              listaUfs.map((dadosUF, index) => (
                <tr key={index}>
                  <td>{dadosUF.id}</td>
                  <td>{dadosUF.uf}</td>
                  <td>{dadosUF.nome}</td>
                </tr>
              ))
            :
            <tr>
              <td colSpan="3">Erro ao carregar dados</td>
            </tr>

          }
          </tbody>
         </table>
        </main>
      </div>
    </>
  );
}
